.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TEMPERATURE\-MACHINE" "1" "August 2019" "" ""
.
.SH "NAME"
\fBtemperature\-machine\fR \- The homebrew data logger
.
.SH "SYNOPSIS"
\fBtemperature\-machine\fR \fB\-i\fR | \fB\-\-init\fR
.
.SH "SPECIAL OPTIONS"
These options must include a double\-dash (\fB\-\-\fR) prefix to escape the parent scripts options\. For example, omitting \fB\-\-\fR for the version option will display the parent script version and not the temperature\-machine\'s version\.
.
.P
\fBtemperature\-machine\fR \fB\-\- \-v\fR | \fB\-\- \-\-version\fR \fBtemperature\-machine\fR \fB\-\- \-h\fR | \fB\-\- \-\-help\fR
.
.SH "DESCRIPTION"
Homebrew temperature data logger based on the DS18B20 sensor\. Logs temperature data from one or more temperature probes and displays some pretty graphs via the web server\.
.
.P
Requires a configuration file to exist before running\. Create one with the \fB\-\-init\fR option\.
.
.P
Run just a \fBsingle\fR server node but as many \fBclients\fR as you like\.
.
.SH "FIND OUT MORE"
See the \fBtemperature\-machine\fR website at temperature\-machine\.com \fIhttp://temperature\-machine\.com\fR\.
.
.SH "OPTIONS"
These options control whether the temperature\-machine runes in client or server mode\.
.
.TP
NO OPTIONS
Run the \fBtemperature\-machine\fR as either a \fBserver\fR or \fBclient\fR as set in the configuration file\.
.
.IP
When run as a \fBserver\fR, the temperature\-machine will be accessible at http://localhost:11900\. One or more DS18B20 probes must be connected and data from these will be logged\.
.
.IP
When run as a \fBclient\fR (and a server is run on another machine) the temperature\-machine will auto\-discover the server\'s location and start sending temperature data to it (again, one or more DS18B20 probes must be connected)\.
.
.TP
\fB\-i\fR, \fB\-\-init\fR
Create the \fBtemperature\-machine\.cfg\fR file under \fB~/\.temperature\fR\. This is required to run the program\.
.
.P
Miscellaneous options:
.
.TP
\fB\-\- \-v\fR, \fB\-\- \-\-version\fR
Display the current version\. This option must be prefixed with the special option \fB\-\-\fR to stop parsing built\-in commands from the parent script (sbt\-native\-packager)\.
.
.TP
\fB\-\- \-h\fR, \fB\-\- \-\-help\fR
Display some help\. This option must be prefixed with the special option \fB\-\-\fR to stop parsing built\-in commands from the parent script (sbt\-native\-packager)\.
.
.SH "EXAMPLES"
.
.nf

$ temperature\-machine \-\-init
$ temperature\-machine \-\-v
$ temperature\-machine \-\- \-\-help
.
.fi
.
.SH "SOURCE"
\fBtemperature\-machine\fR is open source and developed in the open at http://github\.com/tobyweston/temperature\-machine\.
.
.SH "BUGS"
Bugs are tracked on the Github site http://github\.com/tobyweston/temperature\-machine/issues\.
.
.SH "GETTING HELP"
Read the documentation at \fIhttp://temperature\-machine\.com/docs\fR and ask questions on Gitter (\fIhttps://gitter\.im/temperature\-machine/Lobby\fR)\.
.
.SH "COPYRIGHT"
temperature\-machine is Copyright (C) 2016\-2019 Toby Weston
